name: Test Deploy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vendoring:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install project dependencies
        run: npm install

      - name: Run build with npm script
        run: npm run build
      
      - name: Lint and format
        run: npm run lint

      - name: Test worker deployment
        run: npm run deploy -- --dry-run
      
      - name: Run tests
        run: npm run test
