name: Test Deploy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vendoring:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        run: uv sync
      
      - name: Lint and format
        run: |
          uv run ruff format . --check
          uv run ruff check .

      - name: Test worker deployment
        run: uv run pywrangler deploy --dry-run
      
      - name: Run tests
        run: uv run pytest tests
